version: "3.8"

services:
  db:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 15
    ports:
      - "5432:5432"

  api:
    build:
      target: dev_image
    env_file: .env
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      db:
       condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./todolist2:/opt/todolist2
      - ./core:/opt/core

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static/


volumes:
  pg_data:
