version: "3.8"

services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 15


  api:
    image: gysborn/todolist:latest
    env_file: .env
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      db:
       condition: service_healthy

  collect_static:
    image: gysborn/todolist:latest
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static
    command: python manage.py collectstatic -c --no-input



  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "8010:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static



volumes:
  pg_data:
  django_static:
